# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ gha ]
  pull_request:
    branches: [ gha ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: run tests
      run: |
        echo "Directory Contents:"
        ls
      
#     - name: Save artifacts
#       uses: actions/upload-artifact@v2
#       with:
#         name: a11yReport.json
#         path: tower-qa/ui-tests/awx-pf-tests/a11yReport.json
#         if-no-files-found: ignore



# file:///home/runner/work/historiasparadormir/historiasparadormir/app/build/reports/lint-results.xml
